






























i























d: simple.fhir.warehouse
canonical: http://example.org/fhir
name: SimpleFHIRWarehouse
status: draft
version: 0.1.0
fhirVersion: 4.0.1








id: simple.fhir.warehouse
canonical: http://example.org/fhir
name: SimpleFHIRWarehouse
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2026
releaseLabel: ci-build

